### ISSUE TITLE
Custom Fields - Currently Selected

### ISSUE THREAD

**Issue by wesseljt** [singer-io/tap-asana#19]
I really appreciate the addition of custom fields! We are having trouble understanding which value in a custom field is selected for a task. In the example below "Code as NLA" is selected from a dropdown in the asana UI but I'm not sure how to tell which was selected from here.

`
[
  {
    "enabled": true,
    "enum_options": [
      {
        "color": "red",
        "enabled": true,
        "gid": "1171586570372210",
        "name": "Digital Content edit",
        "resource_type": "enum_option"
      },
      {
        "color": "orange",
        "enabled": true,
        "gid": "1171586570372211",
        "name": "Code as NLA",
        "resource_type": "enum_option"
      }]
`

**Comment by smoghul** [comment]
@wesseljt Assuming you're still looking for an answer for this question. Can you send a bigger snippet of your JSON? The code you posted seems like the options of the dropdown. There should be a `enum_value` section right after this which would tell you which value of the drop down was chosen.

Snippets from my JSON:
Custom Field potential options:
```
        "enum_options": [
          {
            "gid": "1119128114335569", 
            "color": "blue-green", 
            "enabled": true, 
            "name": "Confirmed Date", 
            "resource_type": "enum_option"}, 
          {
            "gid": "1119128114335570", 
            "color": "aqua", 
            "enabled": true,
            "name": "Projected Date", 
            "resource_type": "enum_option"
          }
        ], 
```

Chosen Value:
```
"enum_value": 
          {
            "gid": "1119128114335569", 
            "color": "blue-green", 
            "enabled": true, 
            "name": "Confirmed Date", 
            "resource_type": "enum_option"
          }, 
        "name": "Issuance Date", 
        "resource_subtype": "enum", 
        "resource_type": "custom_field", 
        "type": "enum"
      }, 
```

Hope this helps.

**Comment by wesseljt** [comment]
Thank you! Yes got it figured out now.
